### ISSUE TITLE
Game freezes in the middle of fading in the “PRESS START BUTTON” title card

### ISSUE THREAD

**Issue by Aztec2012** [PeterTh/dsfix#14]
Dearest peter, thank you so much for this mod, but ever since the last patch I absolutely cannot start the game with DSFix enabled, even the newest version — it loads save data just fine, but then freezes in the middle of fading in the “PRESS START BUTTON” title card.
I’ve tried using the .ini with zero changes, I’ve tried disabling absolutely everything but no result.

When DSFix remowed game working fine. OS Windows 8.1

**Comment by rosslovas** [comment]
I get the same issue. You can probably fix it by renaming `"C:\Program Files (x86)\Steam\GameOverlayRenderer.dll"` to something else. I also found a workaround a while ago that I just made a pull request for.

**Comment by Aztec2012** [comment]
I fix this issue by renaming folder "movWW"

**Comment by PeterTh** [comment]
Should be fixed by https://github.com/PeterTh/dsfix/pull/15
