### ISSUE TITLE
fps unlock toggle?

### ISSUE THREAD

**Issue by last-partizan** [PeterTh/dsfix#23]
Hello

Is is possible to make toggleFPSUnlock keybinding, so we can play at 60 fps and switch to 30 when long jumping is needed?

**Comment by davidherasp** [comment]
that would be cool

**Comment by last-partizan** [comment]
oh, this is already implemented and bind to backspace key!
dsfixkeys.ini
```
toggle30FPSLimit VK_BACK
```
